### ISSUE TITLE
안녕하세요! eclass 버전을 만들어보려고합니다.

### ISSUE THREAD

**Issue by minsgy** [Gumball12/lmsplusplus#13]
안녕하세요!  먼저 좋은 프로그램을 만들어주셔서 감사합니다.

아이템을 너무 잘 만들어주셔서 코드를 참고 하여 
eclass에도 적용 가능한 익스텐션을 제작해보려고 합니다.  참고해도 될까요?!

**Comment by Gumball12** [comment]
넵 물론이죠 당연하죠 (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
