### ISSUE TITLE
로그인 유지, 배속 기능을 함께 ON을 하면 영상이 재생이 안됩니다.

### ISSUE THREAD

**Issue by H43RO** [Gumball12/lmsplusplus#6]
<img width="832" alt="스크린샷 2020-06-13 오후 7 53 55" src="https://user-images.githubusercontent.com/30336663/84566918-ffc1e280-adaf-11ea-9612-0d971bc81d5a.png">
 
사용 기기 맥북 프로 16인치 고급형이구요, 사용 브라우저는 '네이버 웨일'입니다.
아마 처음 나왔을 때는 잘 돼서  잘 사용하고 있었는데,

어느날 강의 들으려고 lmsplusplus를 활용하여 영상 링크를 접속했는데
재생버튼을 눌러도 재생이 안되고 00:00에 멈춰있는 현상이 발생했습니다.

한가지 발견한 패턴으로는, 영상 링크에 접속하여 영상 탭에서
툴바에서 로그인 유지 기능을 OFF하고 새로고침을 하면 다시 정상작동합니다.

좋은 프로그램 잘 쓰고 있습니다. 감사합니다.

**Comment by Gumball12** [comment]
감사합니다 확인하겠습니다
