### ISSUE TITLE
한 강의에 영상이 2개가 있는 경우 관련

### ISSUE THREAD

**Issue by frost917** [Gumball12/lmsplusplus#8]
일부 교수님이 본인 캠하고 화면하고 따로따로 해놓으시는 경우가 있는데 이럴 경우 본인 캠 영상은 main.mp4에 화면 영상은 sub.mp4에 들어가서 이 부분도 처리해야 할 듯 합니다

**Comment by Gumball12** [comment]
감사합니다 확인하겠습니다
